// <auto-generated />
using System;
using Jh.Abp.MenuManagement.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Jh.Abp.MenuManagement.Migrations
{
    [DbContext(typeof(MenuManagementHttpApiHostMigrationsDbContext))]
    partial class MenuManagementHttpApiHostMigrationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Dm:ValueGenerationStrategy", DmValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("Jh.Abp.MenuManagement.Menus.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasComment("菜单编号");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("CreatorId");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("DeleterId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("DeletionTime");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasComment("菜单描述");

                    b.Property<string>("ExtraProperties")
                        .HasColumnType("NVARCHAR2(8188)")
                        .HasColumnName("ExtraProperties");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasComment("菜单图标");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BIT")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("LastModifierId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasComment("菜单名称");

                    b.Property<string>("ParentCode")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasComment("上级菜单编号");

                    b.Property<int>("Sort")
                        .HasColumnType("INT")
                        .HasComment("同一级别内排序");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasComment("导航路径");

                    b.HasKey("Id");

                    b.ToTable("SysMenu");

                    b
                        .HasComment("菜单");
                });

            modelBuilder.Entity("Jh.Abp.MenuManagement.Menus.MenuAndRoleMap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(36)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("CreatorId");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("VARCHAR(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("VARCHAR(36)");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("RoleId")
                        .HasAnnotation("SqlServer:Include", new[] { "MenuId" });

                    b.ToTable("SysMenuAndRoleMap");

                    b
                        .HasComment("菜单和角色映射表");
                });

            modelBuilder.Entity("Jh.Abp.MenuManagement.Menus.MenuAndRoleMap", b =>
                {
                    b.HasOne("Jh.Abp.MenuManagement.Menus.Menu", "Menu")
                        .WithMany("MenuRoleMaps")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Jh.Abp.MenuManagement.Menus.Menu", b =>
                {
                    b.Navigation("MenuRoleMaps");
                });
#pragma warning restore 612, 618
        }
    }
}
